apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  APP_ENV: "production"
  DATABASE_URL: "postgres-db.production.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: production
type: Opaque
stringData:
  DB_PASSWORD: "SuperSecurePassWord123!"
