pipeline {
    agent any

    environment {
        KUBE_CRED_ID = 'minikube-kubeconfig'
        IMAGE_NAME   = 'my-backend-server:latest'
        SUB_DIR      = 'my-backend-server'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                // Navigate into your subfolder to run docker commands
                dir("${SUB_DIR}") {
                    sh '''
                        docker build -t ${IMAGE_NAME} .
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir("${SUB_DIR}") {
                    withCredentials([file(credentialsId: "${KUBE_CRED_ID}", variable: 'KUBECONFIG')]) {
                        sh '''
                            kubectl apply -f k8s/deployment.yaml
                            kubectl apply -f k8s/service.yaml
                            kubectl rollout restart deployment/nodejs-backend-deployment
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline Completed Successfully!"
        }
        failure {
            echo "Pipeline Failed. Check logs above."
        }
    }
}